
replicaCount: 1

image:
  repository: registry.llince.com/aca-front-demo
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-proto: "http"

  hosts:
    - host: aca.demo.front.com
      paths:
        - /(.*)

resources:

  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 768Mi

nodeSelector: {}

tolerations: []

affinity: {}

NODE_ENV: "production"
NEXTAUTH_URL: https://acawb.lincetechnology.net
NEXTAUTH_SECRET: emFxJG1rbzEy
AUTH_ENABLED: true
API_ENDPOINT_JAVA: http://academoservice/api
JWT_SECRET: shark-some-hedgehogs-are-not-so-cuddly-ow-2020
AUTH_DEGUG: false