{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.imagePullSecrets.registry }}": {
          "username": "{{ .Values.imagePullSecrets.username }}",
          "password": "{{ .Values.imagePullSecrets.password }}",
          "auth": "{{ printf "%s:%s" .Values.imagePullSecrets.username .Values.imagePullSecrets.password | b64enc }}"
        }
      }
    }
{{- end }}