{{- if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "llince.fullname" .) }}
type: Opaque
data:
{{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
