apiVersion: v1
kind: Service
metadata:
  name: {{ include "acafrontenddemo.fullname" . }}
  labels:
    app: acafrontenddemo
    {{- include "acafrontenddemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acafrontenddemo.selectorLabels" . | nindent 4 }}
