{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genericservice.fullname" . }}
  labels:
    app: genericservice
    {{- include "genericservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "genericservice.selectorLabels" . | nindent 4 }}
{{- end }}
