# Default values for mytestchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.lopa.com/genericservice-dev
  tag: latest

#imagePullSecrets:
  #- name : loparegistry
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.genericservice.com
      paths:
        - /(.*)
#  tls:
#    - secretName: my-tls-cert
#      hosts:
#        - local.notificationservice.lopa.com

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

genericSeviceName: generic-sevice-license
genericSeviceKey: keyLicense
dabadaseSecretName: database-ora
databasePassword: dbpassword
databaseUser: dbusername
databaseDriver: dbdriver
databaseUrl: databaseUrl
SQL_PRIVATE_IP: 192.168.1.117
SQL_HOST: database.sql.com