# Default values for mytestchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.llince.com/aca-backend-demo
  tag: latest
  pullPolicy: Always

#imagePullSecrets:
  #- name : loparegistry
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization $http_authorization;
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: aca.demo.service.com
      paths:
        - /
      pathType: Prefix


resources:

  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 768Mi

nodeSelector: {}

tolerations: []

affinity: {}

DB_URL: jdbc:postgresql://database.sql.com:5432/aca_db
CIPHER_SECRET_KEY: E6t187^D43%F
LIQUIBASE_RUN: true
API_JAVA_OPTION: -Xss512k -Xms512m -Xmx1g #-Dlogging.level.com.llh.securitye=DEBUG -Dlogging.level.org.springframework=ERROR
SQL_PRIVATE_IP: 192.168.0.212
SQL_HOST: database.sql.com